---
title: 'Building Packages at Work'
author: 'Karla Fettich'
date: '2021-12-08'
slug: 
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

For the 2021 holiday season, we decided to conclude the year with a meetup all about packages! But not just any packages - packages of reusable code that can make future-you and your coworkers' lives so much easier! Our event was a series of short presentations on the topic of R package development and maintenance in the workplace.

## dataVisEasy - seamless integration of metadata and data for easy and accurate visualizations (Alison Moss)

After getting tired of running similar lines of code over and over again to make minor adjustments to heatmaps and data visualizations, [Alison Moss](https://www.linkedin.com/in/alisonmoss3/) accidentally found herself writing several functions to make all that tweaking easier, eventually turning into it into a package. Now, seamlessly integrating metadata into data visualizations is nice and easy and all those minor tweaks your boss asks for don’t have to be an extra source of stress.

Alison just recently graduated with her PhD from Thomas Jefferson University and is now working at [Rajant Health Inc](https://rajant.com/) as a Computational Biologist. She absolutely loves coding in R and gets way too much enjoyment out of writing and debugging functions to make data analysis and visualizations easy and consistent.

## Nerdify your life (Jess Streeter)

Learn about [Spring Health](https://springhealth.com/)'s internal package, Nerdify, and how it has streamlined several internal processes across our growing data team.

[Jess Streeter](https://www.linkedin.com/in/jessica-streeter-9053a630/) is a Senior Data Scientist at Spring Health. She has spent her entire career working on issues around mental health. When she's not coding away, she enjoys spending time with her family, drinking good beer, and training Jiu Jitsu.

## rocqi - simplifying workflows & reducing technical debt (Jake Riley)

Learn about one of [CHOP](https://www.chop.edu/)’s internal R packages, rocqi. We built this package to improve the process for accessing, formatting, and visualizing data. Categories include quick and easy database connections, ggplot themes, Rmd/dashboard templates, internal datasets, and many helper functions for presenting data to stakeholders. In this talk I’ll discuss the types of solutions we chose to tackle and how package development has made us all better programmers.

[Jake Riley](https://www.linkedin.com/in/jake-riley-70736a3/) is a Senior Data Analyst at the Children’s Hospital of Philadelphia. He works with the Analytics Architecture team to provide centralized solutions for a large team of analysts. His work with rocqi has inspired the development of other R packages including: simplecolors (CRAN), shinyobjects (CRAN), headliner (beta), whereiation (dev), and codereviewr (dev). 

## Links for meetup materials

- Alison Moss' [dataVizEasy GitHub Repo](https://github.com/alisonmoss3/dataVisEasy)
- Jess Streeter's [Nerdify your life](https://docs.google.com/presentation/d/17k8Bkch0HoO79G9boL-nffbeVJIg_YYInG7PVp0gU4A/edit#slide=id.p) slides
- Jake Riley's [GitHub page](https://github.com/rjake)
- [Q&A notes](https://docs.google.com/document/d/15gkRMTa17JZR9qhpmaw-PVAvaem4x6wYxfvaDxTFt0w/edit#)

## Announcements:

Spring Health is Hiring! https://jobs.lever.co/springhealth 

## Watch the recording
To watch a recoring of this event, please head to our [YouTube channel](https://www.youtube.com/channel/UCPque9BaFV9p0hcgImrYBzg) (and why not watch some other R-Ladies videos while you are there!)

<iframe width="560" height="315" src="https://www.youtube.com/embed/lkjcghesAhc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Acknowledgements
Thank you again to Alison, Jess and Jake for sharing their wisdom and experience with us!




