---
title: 'Mapping COVID-19 Vaccination Across the US'
author: 'Amy Goodwin Davies'
date: '2021-07-17'
slug: 
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

[Michelle Chiu](https://www.linkedin.com/in/michelle-chiu-leanmeanmishine/) prepared and delivered the R-Ladies Philly July workshop, which provided a hands-on introduction on how to display data onto relevant geographic locations using R. 

All of Michelle's materials are available in [the GitHub repo for the workshop](https://github.com/mchiu91/us_vaccination_rladies). Michelle got us started with an [introduction](https://github.com/mchiu91/us_vaccination_rladies/blob/main/mapping_us_vaccination_presentation.pdf) that included review of key packages, such as [ggplot2](https://ggplot2.tidyverse.org/) and [cloroplethr](https://cran.r-project.org/package=choroplethr). Michelle then provided a [demo](https://github.com/mchiu91/us_vaccination_rladies/blob/main/r_ladies_ggplot_workshop.Rmd) of how to put these tools together in mapping COVID-19 Vaccination data. We wrapped up with a [data visualization exercise](https://github.com/mchiu91/us_vaccination_rladies/blob/main/r_ladies_ggplot_workshop.Rmd#L112) in breakout rooms.

<blockquote class="twitter-tweet" data-theme="light"><p lang="en" dir="ltr">Want to learn how to display your data onto relevant geographic locations in a ???????? Come to R ladies Philly July workshop ????Mapping COVID-19 Vaccination ????Across the US at 6 p.m EST today!! Sign up at <a href="https://t.co/ZvnnlSwpTY">https://t.co/ZvnnlSwpTY</a> <a href="https://twitter.com/hashtag/RStats?src=hash&amp;ref_src=twsrc%5Etfw">#RStats</a></p>&mdash; R-Ladies Philly (@RLadiesPhilly) <a href="https://twitter.com/RLadiesPhilly/status/1415425484876390407?ref_src=twsrc%5Etfw">July 14, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# About the speaker

[Michelle](https://www.linkedin.com/in/michelle-chiu-leanmeanmishine/) is a graduate student in the Cognition and Neuroscience PhD Program at Temple University. She received her bachelor's degree in Cognitive Neuroscience from Johns Hopkins University in 2014 and continued to earn her master's degree in Human Development at Cornell University in 2017. Her research broadly looks at digital media and risky decision making using a behavioral and neuroimaging approach. In her free time, she enjoys exploring the Philly food scene and practicing yoga!


# Watch the recording

You can watch the recording of the event here:

<iframe width="560" height="315" src="https://www.youtube.com/embed/6Uh2XhbRGmk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Acknowledgements

Many thanks to Michelle for the fantastic workshop!
