---
title: 'Getting Started with Unit Testing in R'
author: 'Chun Su'
date: '2021-11-15'
slug: 
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

[Shannon Pileggi](https://deploy-preview-16--flamboyant-mccarthy-854a9b.netlify.app/about.html) and Gordon Shotwell led a hands-on workshop on how to get started with unit testing in R at the R-Ladies Philly November meetup. This workshop picked up exactly where we left our little `ralph` (aka R-Ladies Philly) package one year ago at the R package development workshop [“Your first R package in 1 hour: Tools that make R package development easy”](https://www.pipinghotdata.com/talks/2020-10-25-your-first-r-package-in-1-hour/). Shannon and Gordon demonstrated handy functions in `usethis` and `devtools`, strategies for writing tests and debugging techniques, and discussed with participants on broad concepts in function writing that facilitate a smoother testing process. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Are you an R developer tasked with writing code for production? Do you worry that code changes will destabilize your code? Then join us at 6pm Philly time TODAY to learn about unit testing! <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/YhEB6X3gRA">https://t.co/YhEB6X3gRA</a></p>&mdash; R-Ladies Philly (@RLadiesPhilly) <a href="https://twitter.com/RLadiesPhilly/status/1458917952493924359?ref_src=twsrc%5Etfw">November 11, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Links for meetup materials
- [Shannon's blog](https://deploy-preview-16--flamboyant-mccarthy-854a9b.netlify.app/posts/2021-11-01-unit-testing/)
- [GitHub repo](https://github.com/shannonpileggi/ralphGetsTested)
- [Q&A notes](https://docs.google.com/document/d/1TlL1xkmgfX7lXJWuJnv-jrGG58sYYFFxR0vfIh5iGCc/edit#)

## Watch the recording
To watch a replay of this event, please head to our YouTube channel (and why not watch some other R-Ladies videos while you are there!)

<iframe width="560" height="315" src="https://www.youtube.com/embed/4bPekjzIYiU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Acknowledgements
Thank you again to Shannon and Gordon for the interactive and informative session!




