---
title: 'February and March 2022: ElderNet Datathon'
author: 'R-Ladies Philly'
date: '2022-03-20'
slug: 
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

This year, we joined forces with our friends at [DataPhilly](https://www.meetup.com/dataphilly/) and partnered with [ElderNet of Lower Merion and Narberth](https://eldernetonline.org/), a wonderful nonprofit organization that facilitates access to healthcare, food security, housing assistance, nursing care, and other necessities for frail older individuals and disabled persons with low to moderate incomes. 

During the [kickoff event](https://youtu.be/2dSYuYJGLk0), ElderNet provided an overview of their services and data needs, and participants then joined one of 3 groups tackling specific topics of interest. Over the subsequent 8 weeks, teams worked tirelessly to not only analyze data, but also summarize their findings into data stories that were presented during the final conclusion event. 


#### Team 1: [ElderNet's impact in the community](https://youtu.be/FeCYaxBP5VY?t=474)

#### Team 2: [Decision-making insights dashboard](https://youtu.be/FeCYaxBP5VY?t=2314)

#### Team 3: [Growth Opportunities and Fun Facts](https://youtu.be/FeCYaxBP5VY?t=4155)

The teams collaborated over [GitHub](https://github.com/rladiesPHL/2022_datathon) and combined their findings into a [comprehensive report](https://github.com/rladiesPHL/2022_datathon/blob/main/analyses/Aging_in_Place_Final_Report.pdf).

### Thank you

We send a huge thank you to our co-organizers at DataPhilly (they do wonderful work for the data community in Philadelphia, make sure to check out their [upcoming meetups](https://www.meetup.com/dataphilly/)!), as well as to our partners at ElderNet who provided us with valuable data and subject matter expertise to help contextualize it. Last but not least, we could not have done this without the dedicated work of the datathon participants who volunteered their time and expertise to analyze, visualize and explain the data so that ElderNet can build a strategy around data insights and continue to make a powerful positive impact in the community. 

This post was authored by Karla Fettich. For more information contact [philly@rladies.org](mailto:philly@rladies.org)
