---
title: 'September 2022: Center City Sips Data Workshop'
author: 'R-Ladies Philly'
date: '2022-09-29'
slug: 
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On the last week of September 2022, 40 R-ladies Philly members joined this wonderful workshop given by [Silvia Canelón](https://silviacanelon.com/) who is a data analyst in the Urban Health Lab at the University of Pennsylvania. We learned how to scrape the data from the [Philly’s 2022 Center City Sips website](https://centercityphila.org/explore-center-city/ccd-sips), and geo-coded the addresses to make an interactive map using geographic data. 

The workshop covers three major steps: 

- Scrape restaurants and addresses from the website with `rvest`

- Geocode the restaurant addresses to obtain geographical coordinates with `tidygeocoder`

- Build an interactive map with `leaflet`.

Miss it? No worries! 

The workshop [slide](slides.silviacanelon.com/2022-ccd-sips) and [Silvia's personal blog](https://silviacanelon.com/blog/2022-ccd-sips) include the complete tutorial for this practice. All the materials can be found on [GitHub](https://github.com/spcanelon/2022-ccd-sips) and in [an RStudio Cloud project](https://rstudio.cloud/content/4597043). You can also watch the workshop recording at our R[ladies Philly YouTube channel](https://www.youtube.com/watch?v=tcfHr0oeOMw).

<iframe width="560" height="315" src="https://www.youtube.com/embed/tcfHr0oeOMw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Besides the workshop, Silvia and the participates also created a list of useful tools and resources:

- https://csspeeper.com Chrome extension is a Smart CSS viewer that inspect styles in a simple, well-organized and beautiful way.

- There was a [YouTube talk on `rvest` and `webscraping`](https://www.youtube.com/watch?v=meapZAH7Jdc) hosted by the Salt Lake City RUG several months ago that might be helpful.

- There is also another [webscraping tutorial](https://www.youtube.com/watch?v=ulESEfyKc1Q) by r-ladies johannesburg by Riva Quiroga.

- [Paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8972108/) and [more resources](https://github.com/spcanelon/geospatial-learning#geocoding-offline ) on geocoding and privacy compliance. Tidygeocoder has some info [on HIPAA-privacy considerations](https://jessecambon.github.io/tidygeocoder/articles/geocoder_services.html#data-privacy) 

- There’s [a wonderful package by Garrick](https://www.garrickadenbuie.com/blog/countdown-v0.4.0/ ) for adding timer to slides. Works with xaringan. You can see it here: 

- [Wiki pages](https://wiki.openstreetmap.org/wiki/Zoom_levels) to estimate how much to zoom in your map.

- [Umami](https://umami.is/) to estimate webpage visit. 


For complete Q&A document, please refer to https://tinyurl.com/rlp-929

## Thank you

We send a huge thank you to our speaker [Silvia Canelón](https://silviacanelon.com/) and all our participates. Follow Silvia at her [blog](https://silviacanelon.com/), [Twitter](https://twitter.com/spcanelon) and [Github](https://github.com/spcanelon) to learn more about R.

This post was authored by Chun Su. For more information contact philly@rladies.org

